### PR TITLE
deal with dropbear only sending data back in small chunks

### PR DESCRIPTION
**Pull request by cj-timothy-sampson**
So this isn't exactly awesome but it's a stop-gap until we get rid of pssh. Note: I'm still testing this in CI but 500 large file scps went through just fine running locally. i.e. don't merge yet but you can already review if you like.

### CODE REVIEW

**Comment by cj-timothy-sampson** [comment]
ping @linasnn and @ArvydasVe any comments here? @ArvydasVe this is the same diff that's included as a patch currently

**Comment by cj-linas-nenorta** [comment]
I tried generating on OpenWrt VM some random file with different sizes, getting it back with scp and checking checksum on both places in a loop with only this problematic part changed:
```
                 while size == LIBSSH2_ERROR_EAGAIN:
                     wait_select(self.session)
```

```
                 if size == LIBSSH2_ERROR_EAGAIN:
                     wait_select(self.session)
```
I didn't see any problems, nothing like:
` # dropbear may or may not EOF terminate the stream it seems`

 Is there any particular dropbear version/device we are having these kinds of problems on?

**Comment by cj-timothy-sampson** [comment]
Well, at least the VM. What you described is what I did too, created files of different sizes and patched `single.py` and retested. With regards to the EOF stream termination, dropbear seems to behave differently on different routers. Let's see if I can recall this correctly - I think it's so that DB on the VM does null terminate and (was it....) the spacerouter DB that doesn't.

So to confirm: all problems were fixed by just making this fix?

```
- while size == LIBSSH2_ERROR_EAGAIN:
-                      wait_select(self.session)
+ if size == LIBSSH2_ERROR_EAGAIN:
+                      wait_select(self.session)
```

For me, decreasing the read chunk size got the failure rate down from 100% to like 1% and then the while/if fix got the last 1%

**Comment by cj-linas-nenorta** [comment]
Yes for me, I ran a small test script with remote.py from test framework:
```
import logging
import random
import os
from remote import Remote
from pssh.utils import enable_logger, logger

enable_logger(logger, level=2)

remote = Remote('192.168.9.1', PASSWD)
remote.run("dd if=/dev/zero of=/tmp/mpstat.out bs=1K count={:d}".format(random.randint(1, 64)))
remote.run("md5sum /tmp/mpstat.out")
os.system("rm -f /tmp/local.out")
remote.get("/tmp/local.out", "/tmp/mpstat.out")
os.system("md5sum /tmp/local.out")
```

**Comment by cj-timothy-sampson** [comment]
OK. I'll push your fix and rerun in CI

**Pull request closed without merging**
